import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
import { Sora } from "next/font/google";
import { ResponsiveNavbar } from "@/components/Home/Navbar/ResponsiveNavbar";
import Footer from "@/components/Home/Footer/Footer";
import ScrollToTpp from "@/components/Helper/ScrollToTpp";
import AnimatedCursor from "react-animated-cursor"

const geistSans = Sora({
  subsets: ['latin'],
  weight: ['100', '200', '300', '400', '500', '600', '700', '800'],
});
export const metadata: Metadata = {
  title: "Bochra Labbene Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="custom-scrollbar">
      <body
        className={geistSans.className}
      >

       

        <ResponsiveNavbar />
        {children}
        <ScrollToTpp />
      </body>
    </html>
  );
}
